### ISSUE TITLE
kzg takes too long, can it be optimized?

### ISSUE THREAD

**Issue by iteyelmp** [ethereumjs/kzg-wasm#15]
`kzg.blobToKzgCommitment(blob)` takes 580-700ms. Assuming a transaction has 3 blobs, it will take about 2 seconds. If there are 6 blobs, this step will take 4 seconds. It takes too long, can it be optimized?

**Comment by acolytec3** [comment]
Unfortunately, this library is entirely dependent on the underlying C library that is transpiled to WASM for the performance of cryptographic operations like this function call. As such, not much I can do since I'm not the author of `c-kzg` and don't have the technical expertise to optimize it further. If you're running your code in a NodeJS environment, you could use the `c-kzg` bindings package the can be installed from NPM and this will likely be more performant as it's running the native C code which is much faster.

Will close this issue here but feel free to reopen if you have further questions.
